### ISSUE TITLE
Carpeta docs/ para agregar documentación

### ISSUE THREAD

**Issue by alejovillores** [trabajo-profesional-fiuba/assignment-service#71]
## Tasks
- [ ] Agregar descripción de los algoritmos y cómo funcionan
- [ ] Agregar diagramas finales de clases
- [ ] Coordinar reunion para charlar sobre `persistence`

## Recursos 
[Python File Projects](https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application)
[DB Design](https://www.lucidchart.com/blog/database-design-best-practices#:~:text=Database%20design%20best%20practices%201%201.%20Keep%20it,look%20for%20the%20right%20fit%20for%20your%20needs)
[DB Design](https://vertabelo.com/blog/best-practices-for-database-design/)
